feat: 체크 스타일 업데이트

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,4 +1,10 @@
 #!/bin/sh
-
 echo '🚀 Running pre-push checks...'
-./gradlew clean build test
+./gradlew clean build -x test
+
+if [ $? -ne 0 ]; then
+  echo "❌ Pre-push checks failed!"
+  exit 1
+fi
+
+echo "✅ All pre-push checks passed!"
